name: "CI Pipeline"

on:
    push:
        branches:
            - main
            - master

jobs:
    on_push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "CI Pipeline running on push"
              run: echo "CI Pipeline running on push"
            - name: "Checkout the code"
              uses: actions/checkout@v4

            - name: "Setup python application"
              uses: actions/setup-python@v5
              with:
                python-version: 3.10 
            
            - name: "Install dependencies"
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller

            - name: "Build the application"
              run: |
                pyinstaller --onefile src/app.py
                echo "Your application is built successfully!"

            - name: "List the repository"
              run: ls -l